app/agent/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, EmailField, PasswordField, SelectField, TextAreaField
from wtforms.validators import DataRequired, ValidationError, EqualTo, Length, Email
from app.models import User, Category, Priority, Status

class TicketForm(FlaskForm):
	subject = StringField('Subject',
		validators=[DataRequired(), Length(max=128)])
	category = SelectField('Category',
		# coerce=int,
		validators=[DataRequired()])
	body = TextAreaField('Body',
		validators=[DataRequired()])

	def __init__(self, *args, **kwargs):
		super(TicketForm, self).__init__(*args, **kwargs)
		self.category.choices = [("", "--- Please select category ---")]+[(category.id, category.category) for category in Category.query.all()]

class TicketUpdateForm(FlaskForm):
	category = SelectField('Category',
		validators=[DataRequired()])
	priority = SelectField('Priority',
		validators=[DataRequired()])
	status = SelectField('Status',
		validators=[DataRequired()])

	def __init__(self, *args, **kwargs):
		super(TicketUpdateForm, self).__init__(*args, **kwargs)
		self.category.choices = [('', '--- Please select category ---')]+[(category.id, category.category)
			for category in Category.query.all()]
		self.priority.choices = [('', '--- Please select priority ---')]+[(priority.id, priority.priority)
			for priority in Priority.query.all()]
		self.status.choices = [('', '--- Please select status ---')]+[(status.id, status.status)
			for status in Status.query.all()]

class EmailUpdateForm(FlaskForm):
	email = EmailField('Email Address',
		validators=[DataRequired(), Email(), Length(max=64)])

	def validate_email(self, email):
		user = User.query.filter_by(email=email.data).first()
		if user:
			raise ValidationError('This email address is already taken')

class PasswordChangeForm(FlaskForm):
	password = PasswordField('New Password',
		validators=[DataRequired(), Length(min=6, max=32)])
	confirm_password = PasswordField('Confirm Password',
		validators=[DataRequired(), EqualTo('password')])

app/agent/views.py
from flask import Blueprint, render_template, redirect, request, url_for, flash
from flask_login import current_user
from sqlalchemy import or_
from app.agent.forms import TicketForm, TicketUpdateForm, EmailUpdateForm, PasswordChangeForm
from app.models import User, Ticket, Comment
from app.decorators import login_required
from app import db, bcrypt
import uuid

agent_blueprint = Blueprint('agent', __name__)

@agent_blueprint.route('/dashboard')
@login_required(role='agent')
def dashboard():
	open = Ticket.query.filter_by(owner_id=current_user.id).filter_by(status_id=1).all()
	resolved = Ticket.query.filter_by(owner_id=current_user.id).filter_by(status_id=2).all()
	pending = Ticket.query.filter_by(owner_id=current_user.id).filter_by(status_id=3).all()
	closed = Ticket.query.filter_by(owner_id=current_user.id).filter_by(status_id=4).all()
	
	return render_template('agent/dashboard.html', open=open, resolved=resolved, pending=pending, closed=closed)

@agent_blueprint.route('/tickets', methods=['GET', 'POST'])
@login_required(role='agent')
def ticket():
	tickets = Ticket.query.order_by(Ticket.id.desc()).all()
	form = TicketForm()
	if form.validate_on_submit():
		public_id = str(uuid.uuid4())
		author_id = current_user.id
		owner_id = None
		priority = 1 # Low priority
		status = 1 # Open status

		ticket = Ticket(
			public_id=public_id,
			subject=form.subject.data,
			body=form.body.data,
			author_id=author_id,
			owner_id=owner_id,
			category_id=int(form.category.data),
			priority_id=priority,
			status_id=status
		)
		
		db.session.add(ticket)
		db.session.commit()
		flash('Ticket has been created.', 'primary')
		return redirect(url_for('agent.ticket'))
	return render_template('agent/ticket.html', tickets=tickets, form=form)

@agent_blueprint.route('/ticket/update/<int:id>/<public_id>', methods=['GET', 'POST'])
@login_required(role='agent')
def update_ticket(id, public_id):
	users = User.query.filter(or_(User.role=='admin', User.role=='agent')).all()
	ticket = Ticket.query.filter_by(id=id, public_id=public_id)
	
	category = 0
	priority = 0
	status = 0
	for i in ticket:
		category = i.category_id
		priority = i.priority_id
		status = i.status_id

	form = TicketUpdateForm(
		category=category,
		priority=priority,
		status=status
	)
	if form.validate_on_submit():
		ticket_id = Ticket.query.get_or_404(id)
		if not request.form['owner_id']:
			ticket_id.owner_id = None
		else:
			ticket_id.owner_id = int(request.form['owner_id'])
		
		ticket_id.category_id = int(form.category.data)
		ticket_id.priority_id = int(form.priority.data)
		ticket_id.status_id = int(form.status.data)
		db.session.commit()
		flash('Ticket has been updated.', 'primary')
		return redirect(url_for('agent.update_ticket', id=id, public_id=public_id))
	return render_template('agent/ticket_update.html', form=form, users=users, ticket=ticket)

@agent_blueprint.route('/ticket/delete/<int:id>', methods=['GET', 'POST'])
@login_required(role='agent')
def delete_ticket(id):
	if request.method == 'POST':
		ticket_id = Ticket.query.get_or_404(id)
		db.session.delete(ticket_id)
		db.session.commit()
		flash('Ticket has been deleted.', 'primary')
		return redirect(url_for('agent.ticket'))
	return redirect(url_for('agent.ticket'))

@agent_blueprint.route('/ticket/comments/<int:id>/<public_id>', methods=['GET', 'POST'])
@login_required(role='agent')
def comment(id, public_id):
	ticket = Ticket.query.filter_by(id=id, public_id=public_id)
	comments = Comment.query.filter(Comment.ticket_id == id).all()
	if request.method == 'POST':
		comment = request.form['comment']
		author_id = int(request.form['author_id'])
		ticket_id = int(request.form['ticket_id'])

		db.session.add(Comment(comment=comment, author_id=author_id, ticket_id=ticket_id))
		db.session.commit()
		flash('Your comment has been sent.', 'primary')
		return redirect(url_for('agent.comment', id=id, public_id=public_id))
	return render_template('agent/ticket_comment.html', ticket=ticket, comments=comments)

@agent_blueprint.route('/ticket/open/<int:id>/<public_id>', methods=['GET', 'POST'])
@login_required(role='agent')
def open_ticket(id, public_id):
	if request.method == 'POST':
		ticket_id = Ticket.query.get_or_404(id)
		ticket_id.status_id = int(request.form['status_id'])

		db.session.commit()
		flash('Ticket has been re-opened.', 'primary')
		return redirect(url_for('agent.comment', id=id, public_id=public_id))
	return redirect(url_for('agent.ticket'))

@agent_blueprint.route('/ticket/close/<int:id>/<public_id>', methods=['GET', 'POST'])
@login_required(role='agent')
def close_ticket(id, public_id):
	if request.method == 'POST':
		ticket_id = Ticket.query.get_or_404(id)
		ticket_id.status_id = int(request.form['status_id'])

		db.session.commit()
		flash('Ticket has been closed.', 'primary')
		return redirect(url_for('agent.comment', id=id, public_id=public_id))
	return redirect(url_for('agent.ticket'))

@agent_blueprint.route('/account_settings', methods=['GET', 'POST'])
@login_required(role='agent')
def account_settings():
	user = User.query.filter(User.id == current_user.id)
	email_form = EmailUpdateForm()
	password_form = PasswordChangeForm()
	if email_form.validate_on_submit():
		user_id = User.query.get_or_404(request.form.get('id'))
		user_id.email = email_form.email.data
		db.session.commit()

		flash('Email has been updated.', 'primary')
		redirect(url_for('agent.account_settings'))
	if password_form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(password_form.password.data).decode('utf-8')
		user_id = User.query.get_or_404(request.form.get('id'))
		user_id.password = hashed_password
		db.session.commit()

		flash('Password has been changed.', 'primary')
		redirect(url_for('agent.account_settings'))
	return render_template('agent/account_settings.html', user=user, email_form=email_form, password_form=password_form)

@agent_blueprint.route('/account/delete/<int:id>', methods=['GET', 'POST'])
@login_required(role='agent')
def delete_account(id):
	if request.method == 'POST':
		user_id = User.query.get_or_404(id)
		db.session.delete(user_id)
		db.session.commit()
		flash('Your account has been permanently deleted.', 'warning')
		return redirect(url_for('auth.logout'))
	return redirect(url_for('agent.account_settings'))

app/templates/agent/account_settings.html
{% from 'macros/_render_input.html' import render_input %}
{% extends 'layouts/dashboard.base.html' %}
{% block title %}Flaskdesk — Account Settings{% endblock %}
{% block content %}

<!-- Content container -->
<div class="container-fluid">
  <!-- Header -->
  <div class="content-box mb-3 content-lighten">
    <h3>Account Settings</h3>
  </div>

  <!-- Alert message -->
  {% include 'includes/alert.html' %}

  <div class="card border-0">
    <div class="card-body">
      <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" id="pills-email-tab" data-toggle="pill" href="#pills-email" role="tab" aria-controls="pills-email" aria-selected="true">Email</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="pills-password-tab" data-toggle="pill" href="#pills-password" role="tab" aria-controls="pills-password" aria-selected="false">Password</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="pills-delete-tab" data-toggle="pill" href="#pills-delete" role="tab" aria-controls="pills-delete" aria-selected="false">Delete Account</a>
        </li>
      </ul>
      <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active" id="pills-email" role="tabpanel" aria-labelledby="pills-email-tab">
          <form action="{{ url_for('agent.account_settings') }}" method="POST" style="padding: 1.25rem;">
            {{ email_form.csrf_token }}
            <div class="form-group row">
              {% for row in user %}
                <input type="hidden" name="id" value="{{ row.id }}">
                <label for="email" class="col-sm-2 col-form-label">Email Address</label>
                <div class="col-sm-5">
                  {{ render_input(email_form.email, "Email", value=row.email) }}
                </div>
              {% endfor %}
            </div>
            <button type="submit" class="btn btn-outline-secondary mt-2">Update</button>
          </form>
        </div>
        <div class="tab-pane fade" id="pills-password" role="tabpanel" aria-labelledby="pills-password-tab">
          <form action="{{ url_for('agent.account_settings') }}" method="POST" style="padding: 1.25rem;">
            {{ password_form.csrf_token }}
            <div class="form-group row">
              <input type="hidden" name="id" value="{{ current_user.id }}">
              <label for="password" class="col-sm-2 col-form-label">New Password</label>
              <div class="col-sm-5">
                {{ render_input(password_form.password, "New Password") }}
              </div>
            </div>
            <div class="form-group row">
              <label for="confirm_password" class="col-sm-2 col-form-label">Confirm Password</label>
              <div class="col-sm-5">
                {{ render_input(password_form.confirm_password, "Confirm Password") }}
              </div>
            </div>
            <button type="submit" class="btn btn-outline-secondary mt-2">Change Password</button>
          </form>
        </div>
        <div class="tab-pane fade" id="pills-delete" role="tabpanel" aria-labelledby="pills-delete-tab">
          <div style="padding: 1.25rem;">
            <p><b>Warning: </b>Once you delete your account, there is no going back. Please be certain.</p>
            <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#deleteModal">
              Delete Account
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Confirmation</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure that you want to delete your account? This will immediately log you out of your account and you will not be able to log in again.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <form action="{{ url_for('agent.delete_account', id=current_user.id) }}" method="POST" role="form">
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
          <input type="submit" class="btn btn-danger" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

app/templates/agent/dashboard.html
{% from 'macros/_dashboard_cards.html' import dashboard_cards %}
{% extends 'layouts/dashboard.base.html' %}
{% block title %}Flaskdesk — Dashboard{% endblock %}
{% block content %}

<!-- Content container -->
<div class="container-fluid">
  <!-- Header -->
  <div class="content-box mb-3 content-lighten">
    <h3>Dashboard</h3>
  </div>

  {{ dashboard_cards(open|length, resolved|length, pending|length, closed|length) }}
</div>

{% endblock %}

app/templates/agent/ticket.html
{% from 'macros/_render_input.html' import render_input %}
{% from 'macros/_render_select.html' import render_select %}
{% extends 'layouts/dashboard.base.html' %}
{% block title %}Flaskdesk — Tickets{% endblock %}
{% block content %}

<!-- Content container -->
<div class="container-fluid">
  <!-- Header -->
  <div class="content-box mb-3 content-lighten">
    <div class="row">
      <div class="col-md-6">
        <h3>Tickets</h3>
      </div>
      <div class="col-md-6">
        <div class="text-right mt-1">
          <button class="btn btn-sm btn-primary" data-toggle="modal" data-target="#createModal">
            Create new
          </button>
        </div>
      </div>
    </div>
  </div>

  <!-- Alert message -->
  {% include 'includes/alert.html' %}

  <table id="table" class="table table-striped table-responsive-sm bg-white">
    <thead>
      <tr>
        <th>ID</th>
        <th>Author</th>
        <th>Subject</th>
        <th>Assigned to</th>
        <th>Priority</th>
        <th>Status</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for row in tickets %}
      <tr>
        <td>
          <a href="{{ url_for('agent.comment', id=row.id, public_id=row.public_id) }}">
            {{ row.public_id[:6] }}
          </a>
        </td>
        <td>
          <a>{{ row.author.name }}</a>
        </td>
        <td>{{ row.subject[:32] }}</td>
        <td>{{ row.owner.name }}</td>
        <td>{{ row.priority.priority }}</td>
        <td>{{ row.status.status }}</td>
        <td>
          <a href="{{ url_for('agent.update_ticket', id=row.id, public_id=row.public_id) }}" class="btn btn-sm btn-primary">
            <i class="fa fa-edit"></i>
          </a>
          <button type="button" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#deleteModal{{ row.id }}">
            <i class="fa fa-trash"></i>
          </button>
        </td>
      </tr>
      <!-- Delete Modal -->
      <div class="modal fade" id="deleteModal{{ row.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel{{ row.id }}" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel{{ row.id }}">Delete Confirmation</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p>Are you sure you want to delete this ticket? This action cannot be undone.</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <form action="{{ url_for('agent.delete_ticket', id=row.id) }}" method="POST" role="form">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <input type="submit" class="btn btn-danger" value="Delete">
              </form>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </tbody>
  </table>
</div>

<!-- Create Modal -->
<div class="modal fade" id="createModal" tabindex="-1" aria-labelledby="createModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="createModalLabel">Create New</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{{ url_for('agent.ticket') }}" method="POST">
          {{ form.csrf_token }}
          <div class="form-group">
            {{ render_input(form.subject, "Subject") }}
          </div>
          <div class="form-group">
            {{ render_select(form.category) }}
          </div>
          <div class="form-group">
            {{ render_input(form.body, "Compose a message...", rows="10") }}
          </div>
          <button type="submit" class="btn btn-primary">Create</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

app/templates/agent/ticket_comment.html
{% extends 'layouts/dashboard.base.html' %}
{% block title %}Flaskdesk — Comments{% endblock %}
{% block content %}

<!-- Content container -->
<div class="container-fluid">
  <!-- Header -->
  <div class="content-box mb-3 content-lighten">
    <div class="row">
      <h3>Comments</h3>
    </div>
  </div>

  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{{ url_for('agent.ticket') }}">Tickets</a></li>
      <li class="breadcrumb-item active" aria-current="page">Comments</li>
    </ol>
  </nav>

  <!-- Alert message -->
  {% include 'includes/alert.html' %}

  <table class="table table-bordered table-responsive-sm ticket-view bg-white">
    <tbody>
      {% for row in ticket %}
        <tr>
          <td class="w-25">Date Created</td>
          <td>{{ row.date_created.strftime('%B %d, %Y — %I:%M %p') }}</td>
        </tr>
        <tr>
          <td>Ticket ID</td>
          <td>{{ row.public_id }}</td>
        </tr>
        <tr>
          <td>Author</td>
          <td>{{ row.author.name }}</td>
        </tr>
        <tr>
          <td>E-mail Address</td>
          <td>{{ row.author.email }}</td>
        </tr>
        <tr>
          <td>Subject</td>
          <td>{{ row.subject }}</td>
        </tr>
        <tr>
          <td>Body</td>
          <td>
            <div class="fr-view">
              {{ row.body|safe }}
            </div>
          </td>
        </tr>
        <tr>
          <td>Assigned to</td>
          <td>{{ row.owner.name }}</td>
        </tr>
        <tr>
          <td>Category</td>
          <td>{{ row.category.category }}</td>
        </tr>
        <tr>
          <td>Priority</td>
          <td>{{ row.priority.priority }}</td>
        </tr>
        <tr>
          <td>Status</td>
          <td>{{ row.status.status }}</td>
        </tr>
        <tr>
          <td>Comments</td>
          <td>
            {% for comment in comments %}
              {% if comment.user.role == 'admin' or comment.user.role == 'agent' %}
                <div class="text-left">
                  <i class="fa fa-user-circle fa-lg text-secondary"></i>
                  <small>
                    <b>{{ comment.user.name }}</b>
                    <span> &bull; </span>
                    {{ comment.date_created.strftime('%m/%d/%Y, %I:%M %p') }}
                  </small>
                </div>
                <div class="alert text-left mb-2">
                  {{ comment.comment|safe }}
                </div>
              {% else %}
                <div class="text-left">
                  <i class="fa fa-user-circle fa-lg text-secondary"></i>
                  <small>
                    <b>{{ comment.user.name }}</b>
                    <span> &bull; </span>
                    {{ comment.date_created.strftime('%m/%d/%Y, %I:%M %p') }}
                  </small>
                </div>
                <div class="alert text-left mb-2">
                  {{ comment.comment|safe }}
                </div>
              {% endif %}
            {% endfor %}
          
            {% if row.status.status != 'Closed' %}
              <form action="{{ url_for('agent.comment', id=row.id, public_id=row.public_id) }}" method="POST">
                <div class="form-group">
                  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                  <input type="hidden" name="author_id" value="{{ current_user.id }}">
                  <input type="hidden" name="ticket_id" value="{{ row.id }}">
                  <textarea class="form-control" id="comment" name="comment" placeholder="Leave a comment..." rows="8" required></textarea>
                </div>
                <button type="submit" class="btn btn-primary float-left">Send</button>
              </form>

              <form action="{{ url_for('agent.close_ticket', id=row.id, public_id=row.public_id) }}" method="POST">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <input type="hidden" name="status_id" value="4">
                <button type="submit" class="btn btn-danger float-right">Close Ticket</button>
              </form>
            {% else %}
              <form action="{{ url_for('agent.open_ticket', id=row.id, public_id=row.public_id) }}" method="POST">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <input type="hidden" name="status_id" value="1">
                <button type="submit" class="btn btn-primary float-right">Re-open Ticket</button>
              </form>
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

app/templates/agent/ticket_update.html
{% from 'macros/_render_select.html' import render_select %}
{% extends 'layouts/dashboard.base.html' %}
{% block title %}Flaskdesk — Update Ticket{% endblock %}
{% block content %}

<!-- Content container -->
<div class="container-fluid">
  <!-- Header -->
  <div class="content-box mb-3 content-lighten">
    <div class="row">
      <h3>Update Ticket</h3>
    </div>
  </div>

  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{{ url_for('agent.ticket') }}">Tickets</a></li>
      <li class="breadcrumb-item active" aria-current="page">Update</li>
    </ol>
  </nav>

  <!-- Alert message -->
  {% include 'includes/alert.html' %}

  <table class="table table-bordered table-responsive-sm ticket-view bg-white">
    <tbody>
      <form action="" method="POST">
      {{ form.csrf_token }}
      {% for row in ticket %}
        <tr>
          <td class="w-25">Date Created</td>
          <td>{{ row.date_created.strftime('%B %d, %Y — %I:%M %p') }}</td>
        </tr>
        <tr>
          <td>Ticket ID</td>
          <td>{{ row.public_id }}</td>
        </tr>
        <tr>
          <td>Author</td>
          <td>{{ row.author.name }}</td>
        </tr>
        <tr>
          <td>E-mail Address</td>
          <td>{{ row.author.email }}</td>
        </tr>
        <tr>
          <td>Subject</td>
          <td>{{ row.subject }}</td>
        </tr>
        <tr>
          <td>Body</td>
          <td>
            <div class="fr-view">
              {{ row.body|safe }}
            </div>
          </td>
        </tr>
        <tr>
          <td>Assign to</td>
          <td>
            <div class="form-group row">
              <div class="col-md-5">
                <select class="custom-select" name="owner_id">
                  <option value="">--- Please select agent ---</option>
                  {% for user in users %}
                    {% if user.id == row.owner.id %}
                      <option value="{{ user.id }}" selected>
                        {{ user.name }} — {{ user.role.capitalize() }}
                      </option>
                    {% else %}
                      <option value="{{ user.id }}">
                        {{ user.name }} — {{ user.role.capitalize() }}
                      </option>
                    {% endif %}
                  {% endfor %}
                </select>
              </div>
            </div>
          </td>
        </tr>
        <tr>
          <td>Category</td>
          <td>
            <div class="form-group row">
              <div class="col-md-5">
                {{ render_select(form.category) }}
              </div>
            </div>
          </td>
        </tr>
        <tr>
          <td>Priority</td>
          <td>
            <div class="form-group row">
              <div class="col-md-5">
                {{ render_select(form.priority) }}
              </div>
            </div>
          </td>
        </tr>
        <tr>
          <td>Status</td>
          <td>
            <div class="form-group row">
              <div class="col-md-5">
                {{ render_select(form.status) }}
              </div>
            </div>
          </td>
        </tr>
        <tr>
          <td></td>
          <td>
            <button type="submit" class="btn btn-primary">Update</button>
          </td>
        </tr>
      {% endfor %}
      </form>
    </tbody>
  </table>
</div>

{% endblock %}